development:
  publishable_key: "<%= ENV['STRIPE_PUBLISHABLE'] %>"
  secret_key: "<%= ENV['STRIPE_SECRET'] %>"
production:
  publishable_key: "<%= ENV['STRIPE_PUBLISHABLE'] %>"
  secret_key: "<%= ENV['STRIPE_SECRET'] %>"
